Update created dockerfiles with synopsys-detect jar name

diff --git a/java/11/alpine/3.13/detect/8.11.2/standard/Dockerfile b/java/11/alpine/3.13/detect/8.11.2/standard/Dockerfile
--- a/java/11/alpine/3.13/detect/8.11.2/standard/Dockerfile
+++ b/java/11/alpine/3.13/detect/8.11.2/standard/Dockerfile
@@ -15,7 +15,7 @@ ENV BDS_JAVA_HOME=/usr/lib/jvm/java-11-openjdk
 
 ARG DETECT_SOURCE=https://repo.blackduck.com/bds-integrations-release/com/synopsys/integration/synopsys-detect/8.11.2/synopsys-detect-8.11.2.jar
 
-RUN if [ $(curl --silent -L -w '%{http_code}' -o /detect.jar --create-dirs ${DETECT_SOURCE}) != "200" ]; then echo "Unable to download Detect jar from ${DETECT_SOURCE}"; exit 1; fi
+RUN if [ $(curl --silent -L -w '%{http_code}' -o /synopsys-detect.jar --create-dirs ${DETECT_SOURCE}) != "200" ]; then echo "Unable to download Detect jar from ${DETECT_SOURCE}"; exit 1; fi
 
 # Define Docker Image entrypoint
 ENTRYPOINT ["java", "-jar", "/synopsys-detect.jar", "--detect.source.path=/source", "--detect.output.path=/output", "--detect.phone.home.passthrough.invoked.by.image=true"]
